name: CI

on: 
  push:
    branches:    
      - master # Push events on master branch

jobs:
  build:
    name: Build on node 12 and ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        version: 12

    - name: npm install and build
      run: |
        npm install
        npm run build --if-present

    - name: ssh deployment
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        USERNAME: ${{ secrets.FTP_USERNAME }}
        PASSWORD: ${{ secrets.FTP_PASSWORD }}
      with:
        source: dist/*
        target: ${{ secrets.TARGET_FOLDER }}
        strip_components: 1
